# NOTE: This is an auto-generated file. Please do not edit this file manually.
from airflow import DAG
from airflow.utils import timezone
from astro import sql as aql
from astro.sql.table import Table

with DAG(
    dag_id="sql_files",
    start_date=timezone.parse("2022-09-28 00:00:00"),
    schedule_interval=None,
) as dag:
    a = aql.transform_sql(
        sql="_target/a.sql",
        parameters={
        },
        op_kwargs={
            "output_table": Table(
                name="a",
            ),
        },
        task_id="a",
    )
    b = aql.transform_sql(
        sql="_target/b.sql",
        parameters={
            "a": a,
        },
        op_kwargs={
            "output_table": Table(
                name="b",
            ),
        },
        task_id="b",
    )
    c = aql.transform_sql(
        sql="_target/c.sql",
        parameters={
            "a": a,
            "b": b,
        },
        op_kwargs={
            "output_table": Table(
                name="c",
            ),
        },
        task_id="c",
    )
    sub_dir__a = aql.transform_sql(
        sql="_target/sub_dir/a.sql",
        parameters={
        },
        op_kwargs={
            "output_table": Table(
                name="a",
            ),
        },
        task_id="sub_dir__a",
    )
