CONFIG_DIR = "config"
GLOBAL_CONFIG_FILENAME = "global.yml"
CONFIG_FILENAME = "configuration.yml"

DEFAULT_ENVIRONMENT = "default"
DEFAULT_AIRFLOW_HOME = f".airflow/{DEFAULT_ENVIRONMENT}"
DEFAULT_DAGS_FOLDER = ".airflow/dags"
DEFAULT_DATA_DIR = "data"

GENERATED_WORKFLOW_INCLUDE_DIRECTORY = "include"

# Connection types
SQLITE_CONN_TYPE = "sqlite"
