import os

DEFAULT_CHUNK_SIZE = 1000000
PYPI_PROJECT_NAME = "astro-projects"
DEFAULT_SCHEMA = "tmp_astro"
POSTGRES = "postgres"
BIGQUERY = "bigquery"
SQLITE = "sqlite"
SNOWFLAKE = "snowflake"
SUPPORTED_DATABASES = [POSTGRES, BIGQUERY, SQLITE, SNOWFLAKE]
