# NOTE: This is an auto-generated file. Please do not edit this file manually.
from airflow import DAG
from airflow.utils import timezone
from astro import sql as aql
from astro.table import Table

with DAG(
    dag_id="advanced",
    start_date=timezone.parse("2022-10-05 06:47:15.790544"),
    schedule_interval=None,
) as dag:
    source__imdb_movies = aql.transform_file(
        file_path="_target/advanced/source/imdb_movies.sql",
        parameters={
        },
        conn_id="postgres_conn",
        op_kwargs={
            "output_table": Table(
                name="imdb_movies",
            ),
        },
        task_id="source__imdb_movies",
    )
    source__last_five_animations = aql.transform_file(
        file_path="_target/advanced/source/last_five_animations.sql",
        parameters={
            "source__imdb_movies": source__imdb_movies,
        },
        schema="public",
        op_kwargs={
            "output_table": Table(
                name="last_five_animations",
            ),
        },
        task_id="source__last_five_animations",
    )
    source__top_five_animations = aql.transform_file(
        file_path="_target/advanced/source/top_five_animations.sql",
        parameters={
            "source__imdb_movies": source__imdb_movies,
        },
        op_kwargs={
            "output_table": Table(
                name="top_five_animations",
            ),
        },
        task_id="source__top_five_animations",
    )
    mart__union_top_and_last = aql.transform_file(
        file_path="_target/advanced/mart/union_top_and_last.sql",
        parameters={
            "source__last_five_animations": source__last_five_animations,
            "source__top_five_animations": source__top_five_animations,
        },
        database="postgres",
        op_kwargs={
            "output_table": Table(
                name="union_top_and_last",
            ),
        },
        task_id="mart__union_top_and_last",
    )
