# NOTE: This is an auto-generated file. Please do not edit this file manually.
from pathlib import Path

from airflow import DAG
from airflow.utils import timezone
from astro import sql as aql
from astro.table import Table

DAGS_DIRECTORY = Path(__file__).parent.as_posix()

with DAG(
    dag_id="simple",
    start_date=timezone.parse("2020-01-01 00:00:00"),
    schedule_interval=None,
) as dag:
    imdb_movies = aql.transform_file(
        file_path=f"{DAGS_DIRECTORY}/_target/simple/imdb_movies.sql",
        parameters={
        },
        conn_id="postgres_conn",
        op_kwargs={
            "output_table": Table(
                name="imdb_movies",
            ),
        },
        task_id="imdb_movies",
    )
    last_five_animations = aql.transform_file(
        file_path=f"{DAGS_DIRECTORY}/_target/simple/last_five_animations.sql",
        parameters={
            "imdb_movies": imdb_movies,
        },
        op_kwargs={
            "output_table": Table(
                name="last_five_animations",
            ),
        },
        task_id="last_five_animations",
    )
    top_five_animations = aql.transform_file(
        file_path=f"{DAGS_DIRECTORY}/_target/simple/top_five_animations.sql",
        parameters={
            "imdb_movies": imdb_movies,
        },
        op_kwargs={
            "output_table": Table(
                name="top_five_animations",
            ),
        },
        task_id="top_five_animations",
    )
    union_top_and_last = aql.transform_file(
        file_path=f"{DAGS_DIRECTORY}/_target/simple/union_top_and_last.sql",
        parameters={
            "last_five_animations": last_five_animations,
            "top_five_animations": top_five_animations,
        },
        op_kwargs={
            "output_table": Table(
                name="union_top_and_last",
            ),
        },
        task_id="union_top_and_last",
    )
