# NOTE: This is an auto-generated file. Please do not edit this file manually.
from airflow import DAG
from airflow.utils import timezone
from astro import sql as aql
from astro.sql.table import Table

with DAG(
    dag_id="simple",
    start_date=timezone.parse("2022-10-05 06:47:20.684131"),
    schedule_interval=None,
) as dag:
    imdb_movies = aql.transform_file(
        file_path="_target/simple/imdb_movies.sql",
        parameters={
        },
        conn_id="postgres_conn",
        op_kwargs={
            "output_table": Table(
                name="imdb_movies",
            ),
        },
        task_id="imdb_movies",
    )
    last_five_animations = aql.transform_file(
        file_path="_target/simple/last_five_animations.sql",
        parameters={
            "imdb_movies": imdb_movies,
        },
        op_kwargs={
            "output_table": Table(
                name="last_five_animations",
            ),
        },
        task_id="last_five_animations",
    )
    top_five_animations = aql.transform_file(
        file_path="_target/simple/top_five_animations.sql",
        parameters={
            "imdb_movies": imdb_movies,
        },
        op_kwargs={
            "output_table": Table(
                name="top_five_animations",
            ),
        },
        task_id="top_five_animations",
    )
    union_top_and_last = aql.transform_file(
        file_path="_target/simple/union_top_and_last.sql",
        parameters={
            "last_five_animations": last_five_animations,
            "top_five_animations": top_five_animations,
        },
        op_kwargs={
            "output_table": Table(
                name="union_top_and_last",
            ),
        },
        task_id="union_top_and_last",
    )
